apiVersion: v1
kind: ConfigMap
metadata:
  name: marketplace-config
data:
  NODE_ENV: production
  NEXT_PUBLIC_ENVIRONMENT: production
  NEXT_PUBLIC_SOLANA_ENDPOINT: "https://rpc.helius.xyz/?api-key=6b1ccd35-ba2d-472a-8f54-9ac2c3c40b8b"
  NEXT_PUBLIC_INDEXER_GRAPHQL_URL: https://graph.holaplex.com/v1
